#!/bin/bash
#SBATCH --job-name=gene
#SBATCH --ntasks=1
#SBATCH --mem=5G
#SBATCH --partition=express
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=tmamidi@uab.edu
#SBATCH --output=../logs/%x_%A_%a.log
#SBATCH --array=3-5

module reset
module load Anaconda3/2020.02
source activate training

n=$SLURM_ARRAY_TASK_ID  #19622
FILES=(/data/project/worthey_lab/projects/experimental_pipelines/tarun/ditto/data/processed/dbnsfp_genes/*)
gene=${FILES[$SLURM_ARRAY_TASK_ID]}

echo "${gene##*/}"


python predictions.py -i /data/project/worthey_lab/projects/experimental_pipelines/tarun/ditto/data/processed/dbnsfp_genes/${gene##*/}/dbNSFP_${gene##*/}_variants.tsv.gz --ditto /data/project/worthey_lab/projects/experimental_pipelines/tarun/ditto/data/processed/dbnsfp_predictions/${gene##*/}_ditto_predictions.csv.gz
