name: testing

channels:
  - conda-forge
  - anaconda
  - bioconda

dependencies:
  - python=3.9.7
  - pandas=1.3.3
  - numpy=1.19.5
  - scikit-learn=0.24.2
  - imbalanced-learn=0.7.0
  - scipy=1.7.1
  - shap=0.39.0
  - bcftools=1.13
  - pip=21.2.4
  - bioconda::snakefmt==0.4.0
  - bioconda::snakemake==6.0.5
  - seaborn=0.11.2
  - black=20.8b1
  - pylint=2.11.1
  - lz4=3.1.3
  - gpy=1.10.0
