# columns to be needed in dataset
columns:
 - '#chr'
 - pos(1-based)
 - ref
 - alt
 - aaref
 - aaalt
 - genename
 - Ensembl_geneid
 - Ensembl_transcriptid
 - Ensembl_proteinid
 - Uniprot_acc
 - cds_strand
 - SIFT_score
 - SIFT_converted_rankscore
 - SIFT_pred
 - SIFT4G_score
 - SIFT4G_converted_rankscore
 - SIFT4G_pred
 - Polyphen2_HDIV_score
 - Polyphen2_HDIV_rankscore
 - Polyphen2_HDIV_pred
 - Polyphen2_HVAR_score
 - Polyphen2_HVAR_rankscore
 - Polyphen2_HVAR_pred
 - LRT_score
 - LRT_converted_rankscore
 - LRT_pred
 - LRT_Omega
 - MutationTaster_converted_rankscore
 - MutationAssessor_score
 - MutationAssessor_rankscore
 - MutationAssessor_pred
 - FATHMM_score
 - FATHMM_converted_rankscore
 - FATHMM_pred
 - PROVEAN_score
 - PROVEAN_converted_rankscore
 - PROVEAN_pred
 - VEST4_score
 - VEST4_rankscore
 - MetaSVM_score
 - MetaSVM_rankscore
 - MetaSVM_pred
 - MetaLR_score
 - MetaLR_rankscore
 - MetaLR_pred
 - Reliability_index
 - MetaRNN_score
 - MetaRNN_rankscore
 - MetaRNN_pred
 - M-CAP_score
 - M-CAP_rankscore
 - M-CAP_pred
 - REVEL_score
 - REVEL_rankscore
 - MutPred_score
 - MutPred_rankscore
 - MVP_score
 - MVP_rankscore
 - MPC_score
 - MPC_rankscore
 - PrimateAI_score
 - PrimateAI_rankscore
 - PrimateAI_pred
 - DEOGEN2_score
 - DEOGEN2_rankscore
 - DEOGEN2_pred
 - BayesDel_addAF_score
 - BayesDel_addAF_rankscore
 - BayesDel_addAF_pred
 - BayesDel_noAF_score
 - BayesDel_noAF_rankscore
 - BayesDel_noAF_pred
 - ClinPred_score
 - ClinPred_rankscore
 - ClinPred_pred
 - LIST-S2_score
 - LIST-S2_rankscore
 - LIST-S2_pred
 - CADD_raw
 - CADD_raw_rankscore
 - CADD_phred
 - CADD_raw_hg19
 - CADD_raw_rankscore_hg19
 - CADD_phred_hg19
 - DANN_score
 - DANN_rankscore
 - fathmm-MKL_coding_score
 - fathmm-MKL_coding_rankscore
 - fathmm-MKL_coding_pred
 - fathmm-XF_coding_score
 - fathmm-XF_coding_rankscore
 - fathmm-XF_coding_pred
 - Eigen-raw_coding
 - Eigen-raw_coding_rankscore
 - Eigen-phred_coding
 - Eigen-PC-raw_coding
 - Eigen-PC-raw_coding_rankscore
 - Eigen-PC-phred_coding
 - GenoCanyon_score
 - GenoCanyon_rankscore
 - integrated_fitCons_score
 - integrated_fitCons_rankscore
 - integrated_confidence_value
 - GM12878_fitCons_score
 - GM12878_fitCons_rankscore
 - GM12878_confidence_value
 - H1-hESC_fitCons_score
 - H1-hESC_fitCons_rankscore
 - H1-hESC_confidence_value
 - HUVEC_fitCons_score
 - HUVEC_fitCons_rankscore
 - HUVEC_confidence_value
 - LINSIGHT
 - LINSIGHT_rankscore
 - GERP++_NR
 - GERP++_RS
 - GERP++_RS_rankscore
 - phyloP100way_vertebrate
 - phyloP100way_vertebrate_rankscore
 - phyloP30way_mammalian
 - phyloP30way_mammalian_rankscore
 - phyloP17way_primate
 - phyloP17way_primate_rankscore
 - phastCons100way_vertebrate
 - phastCons100way_vertebrate_rankscore
 - phastCons30way_mammalian
 - phastCons30way_mammalian_rankscore
 - phastCons17way_primate
 - phastCons17way_primate_rankscore
 - SiPhy_29way_logOdds
 - SiPhy_29way_logOdds_rankscore
 - bStatistic
 - bStatistic_converted_rankscore
 - 1000Gp3_AF
 - 1000Gp3_AFR_AF
 - 1000Gp3_EUR_AF
 - 1000Gp3_AMR_AF
 - 1000Gp3_EAS_AF
 - 1000Gp3_SAS_AF
 - TWINSUK_AF
 - ALSPAC_AF
 - UK10K_AF
 - ESP6500_AA_AF
 - ESP6500_EA_AF
 - ExAC_AF
 - ExAC_Adj_AF
 - ExAC_AFR_AF
 - ExAC_AMR_AF
 - ExAC_EAS_AF
 - ExAC_FIN_AF
 - ExAC_NFE_AF
 - ExAC_SAS_AF
 - ExAC_nonTCGA_AF
 - ExAC_nonTCGA_Adj_AF
 - ExAC_nonTCGA_AFR_AF
 - ExAC_nonTCGA_AMR_AF
 - ExAC_nonTCGA_EAS_AF
 - ExAC_nonTCGA_FIN_AF
 - ExAC_nonTCGA_NFE_AF
 - ExAC_nonTCGA_SAS_AF
 - ExAC_nonpsych_AF
 - ExAC_nonpsych_Adj_AF
 - ExAC_nonpsych_AFR_AF
 - ExAC_nonpsych_AMR_AF
 - ExAC_nonpsych_EAS_AF
 - ExAC_nonpsych_FIN_AF
 - ExAC_nonpsych_NFE_AF
 - ExAC_nonpsych_SAS_AF
 - gnomAD_exomes_AF
 - gnomAD_exomes_AFR_AF
 - gnomAD_exomes_AMR_AF
 - gnomAD_exomes_ASJ_AF
 - gnomAD_exomes_EAS_AF
 - gnomAD_exomes_FIN_AF
 - gnomAD_exomes_NFE_AF
 - gnomAD_exomes_SAS_AF
 - gnomAD_exomes_POPMAX_AF
 - gnomAD_exomes_controls_AF
 - gnomAD_exomes_non_neuro_AF
 - gnomAD_exomes_non_cancer_AF
 - gnomAD_exomes_non_topmed_AF
 - gnomAD_exomes_controls_AFR_AF
 - gnomAD_exomes_controls_AMR_AF
 - gnomAD_exomes_controls_ASJ_AF
 - gnomAD_exomes_controls_EAS_AF
 - gnomAD_exomes_controls_FIN_AF
 - gnomAD_exomes_controls_NFE_AF
 - gnomAD_exomes_controls_SAS_AF
 - gnomAD_exomes_controls_POPMAX_AF
 - gnomAD_exomes_non_neuro_AFR_AF
 - gnomAD_exomes_non_neuro_AMR_AF
 - gnomAD_exomes_non_neuro_ASJ_AF
 - gnomAD_exomes_non_neuro_EAS_AF
 - gnomAD_exomes_non_neuro_FIN_AF
 - gnomAD_exomes_non_neuro_NFE_AF
 - gnomAD_exomes_non_neuro_SAS_AF
 - gnomAD_exomes_non_neuro_POPMAX_AF
 - gnomAD_exomes_non_cancer_AFR_AF
 - gnomAD_exomes_non_cancer_AMR_AF
 - gnomAD_exomes_non_cancer_ASJ_AF
 - gnomAD_exomes_non_cancer_EAS_AF
 - gnomAD_exomes_non_cancer_FIN_AF
 - gnomAD_exomes_non_cancer_NFE_AF
 - gnomAD_exomes_non_cancer_SAS_AF
 - gnomAD_exomes_non_cancer_POPMAX_AF
 - gnomAD_exomes_non_topmed_AFR_AF
 - gnomAD_exomes_non_topmed_AMR_AF
 - gnomAD_exomes_non_topmed_ASJ_AF
 - gnomAD_exomes_non_topmed_EAS_AF
 - gnomAD_exomes_non_topmed_FIN_AF
 - gnomAD_exomes_non_topmed_NFE_AF
 - gnomAD_exomes_non_topmed_SAS_AF
 - gnomAD_exomes_non_topmed_POPMAX_AF
 - gnomAD_genomes_AF
 - gnomAD_genomes_POPMAX_AF
 - gnomAD_genomes_AFR_AF
 - gnomAD_genomes_AMI_AF
 - gnomAD_genomes_AMR_AF
 - gnomAD_genomes_ASJ_AF
 - gnomAD_genomes_EAS_AF
 - gnomAD_genomes_FIN_AF
 - gnomAD_genomes_MID_AF
 - gnomAD_genomes_NFE_AF
 - gnomAD_genomes_SAS_AF
 - gnomAD_genomes_controls_and_biobanks_AF
 - gnomAD_genomes_non_neuro_AF
 - gnomAD_genomes_non_cancer_AF
 - gnomAD_genomes_non_topmed_AF
 - gnomAD_genomes_controls_and_biobanks_AFR_AF
 - gnomAD_genomes_controls_and_biobanks_AMI_AF
 - gnomAD_genomes_controls_and_biobanks_AMR_AF
 - gnomAD_genomes_controls_and_biobanks_ASJ_AF
 - gnomAD_genomes_controls_and_biobanks_EAS_AF
 - gnomAD_genomes_controls_and_biobanks_FIN_AF
 - gnomAD_genomes_controls_and_biobanks_MID_AF
 - gnomAD_genomes_controls_and_biobanks_NFE_AF
 - gnomAD_genomes_controls_and_biobanks_SAS_AF
 - gnomAD_genomes_non_neuro_AFR_AF
 - gnomAD_genomes_non_neuro_AMI_AF
 - gnomAD_genomes_non_neuro_AMR_AF
 - gnomAD_genomes_non_neuro_ASJ_AF
 - gnomAD_genomes_non_neuro_EAS_AF
 - gnomAD_genomes_non_neuro_FIN_AF
 - gnomAD_genomes_non_neuro_MID_AF
 - gnomAD_genomes_non_neuro_NFE_AF
 - gnomAD_genomes_non_neuro_SAS_AF
 - gnomAD_genomes_non_cancer_AFR_AF
 - gnomAD_genomes_non_cancer_AMI_AF
 - gnomAD_genomes_non_cancer_AMR_AF
 - gnomAD_genomes_non_cancer_ASJ_AF
 - gnomAD_genomes_non_cancer_EAS_AF
 - gnomAD_genomes_non_cancer_FIN_AF
 - gnomAD_genomes_non_cancer_MID_AF
 - gnomAD_genomes_non_cancer_NFE_AF
 - gnomAD_genomes_non_cancer_SAS_AF
 - gnomAD_genomes_non_topmed_AFR_AF
 - gnomAD_genomes_non_topmed_AMI_AF
 - gnomAD_genomes_non_topmed_AMR_AF
 - gnomAD_genomes_non_topmed_ASJ_AF
 - gnomAD_genomes_non_topmed_EAS_AF
 - gnomAD_genomes_non_topmed_FIN_AF
 - gnomAD_genomes_non_topmed_MID_AF
 - gnomAD_genomes_non_topmed_NFE_AF
 - gnomAD_genomes_non_topmed_SAS_AF
 - clinvar_clnsig
 - clinvar_review
 - Interpro_domain

ClinicalSignificance:
 - Uncertain_significance
 - Pathogenic
 - Likely_pathogenic
 - Benign
 - Likely_benign
 - Benign/Likely_benign
 - Pathogenic/Likely_pathogenic

Clinsig_train:
  -  Benign
  -  Pathogenic
  -  Likely_pathogenic
  -  Likely_benign

Clinsig_test:
  -  Pathogenic/Likely_pathogenic
  -  Benign/Likely_benign


CLNREVSTAT: #https://www.ncbi.nlm.nih.gov/clinvar/docs/review_status/
  -  practice_guideline
  -  reviewed_by_expert_panel
  -  criteria_provided,_multiple_submitters,_no_conflicts
  -  criteria_provided,_single_submitter

col_conv:
  -  MutationTaster_score
  -  MutationAssessor_score
  -  PROVEAN_score
  -  VEST4_score
  -  FATHMM_score
  -  GERP

ML_VAR:
    -   '#chr'
    -   pos(1-based)
    -   ref
    -   alt
    -   aaref
    -   aaalt
    -   genename
    -   Ensembl_geneid
    -   Ensembl_transcriptid
    -   Ensembl_proteinid
    -   Uniprot_acc
    -   clinvar_review
    -   Interpro_domain

var:
    -   '#chr'
    -   pos(1-based)
    -   ref
    -   alt
    -   aaref
    -   aaalt
    -   genename
    -   Ensembl_geneid
    -   Ensembl_transcriptid
    -   Ensembl_proteinid
    -   Uniprot_acc
    -   clinvar_review
    -   Interpro_domain

Consequence:
  -  missense_variant
  -  missense_variant&splice_region_variant
  -  stop_gained
  -  start_lost&NMD_transcript_variant
  -  start_lost
  -  stop_gained&splice_region_variant
  -  stop_gained&NMD_transcript_variant
  -  missense_variant&splice_region_variant&NMD_transcript_variant
  -  stop_gained&splice_region_variant&NMD_transcript_variant
  -  start_lost&splice_region_variant
  -  stop_lost&splice_region_variant
  -  stop_lost&splice_region_variant&NMD_transcript_variant
  -  splice_donor_variant&missense_variant
  -  start_lost&splice_region_variant&NMD_transcript_variant

allele_freq_columns:
 - 1000Gp3_AF
 - 1000Gp3_AFR_AF
 - 1000Gp3_EUR_AF
 - 1000Gp3_AMR_AF
 - 1000Gp3_EAS_AF
 - 1000Gp3_SAS_AF
 - TWINSUK_AF
 - ALSPAC_AF
 - UK10K_AF
 - ESP6500_AA_AF
 - ESP6500_EA_AF
 - ExAC_AF
 - ExAC_Adj_AF
 - ExAC_AFR_AF
 - ExAC_AMR_AF
 - ExAC_EAS_AF
 - ExAC_FIN_AF
 - ExAC_NFE_AF
 - ExAC_SAS_AF
 - ExAC_nonTCGA_AF
 - ExAC_nonTCGA_Adj_AF
 - ExAC_nonTCGA_AFR_AF
 - ExAC_nonTCGA_AMR_AF
 - ExAC_nonTCGA_EAS_AF
 - ExAC_nonTCGA_FIN_AF
 - ExAC_nonTCGA_NFE_AF
 - ExAC_nonTCGA_SAS_AF
 - ExAC_nonpsych_AF
 - ExAC_nonpsych_Adj_AF
 - ExAC_nonpsych_AFR_AF
 - ExAC_nonpsych_AMR_AF
 - ExAC_nonpsych_EAS_AF
 - ExAC_nonpsych_FIN_AF
 - ExAC_nonpsych_NFE_AF
 - ExAC_nonpsych_SAS_AF
 - gnomAD_exomes_AF
 - gnomAD_exomes_AFR_AF
 - gnomAD_exomes_AMR_AF
 - gnomAD_exomes_ASJ_AF
 - gnomAD_exomes_EAS_AF
 - gnomAD_exomes_FIN_AF
 - gnomAD_exomes_NFE_AF
 - gnomAD_exomes_SAS_AF
 - gnomAD_exomes_POPMAX_AF
 - gnomAD_exomes_controls_AF
 - gnomAD_exomes_non_neuro_AF
 - gnomAD_exomes_non_cancer_AF
 - gnomAD_exomes_non_topmed_AF
 - gnomAD_exomes_controls_AFR_AF
 - gnomAD_exomes_controls_AMR_AF
 - gnomAD_exomes_controls_ASJ_AF
 - gnomAD_exomes_controls_EAS_AF
 - gnomAD_exomes_controls_FIN_AF
 - gnomAD_exomes_controls_NFE_AF
 - gnomAD_exomes_controls_SAS_AF
 - gnomAD_exomes_controls_POPMAX_AF
 - gnomAD_exomes_non_neuro_AFR_AF
 - gnomAD_exomes_non_neuro_AMR_AF
 - gnomAD_exomes_non_neuro_ASJ_AF
 - gnomAD_exomes_non_neuro_EAS_AF
 - gnomAD_exomes_non_neuro_FIN_AF
 - gnomAD_exomes_non_neuro_NFE_AF
 - gnomAD_exomes_non_neuro_SAS_AF
 - gnomAD_exomes_non_neuro_POPMAX_AF
 - gnomAD_exomes_non_cancer_AFR_AF
 - gnomAD_exomes_non_cancer_AMR_AF
 - gnomAD_exomes_non_cancer_ASJ_AF
 - gnomAD_exomes_non_cancer_EAS_AF
 - gnomAD_exomes_non_cancer_FIN_AF
 - gnomAD_exomes_non_cancer_NFE_AF
 - gnomAD_exomes_non_cancer_SAS_AF
 - gnomAD_exomes_non_cancer_POPMAX_AF
 - gnomAD_exomes_non_topmed_AFR_AF
 - gnomAD_exomes_non_topmed_AMR_AF
 - gnomAD_exomes_non_topmed_ASJ_AF
 - gnomAD_exomes_non_topmed_EAS_AF
 - gnomAD_exomes_non_topmed_FIN_AF
 - gnomAD_exomes_non_topmed_NFE_AF
 - gnomAD_exomes_non_topmed_SAS_AF
 - gnomAD_exomes_non_topmed_POPMAX_AF
 - gnomAD_genomes_AF
 - gnomAD_genomes_POPMAX_AF
 - gnomAD_genomes_AFR_AF
 - gnomAD_genomes_AMI_AF
 - gnomAD_genomes_AMR_AF
 - gnomAD_genomes_ASJ_AF
 - gnomAD_genomes_EAS_AF
 - gnomAD_genomes_FIN_AF
 - gnomAD_genomes_MID_AF
 - gnomAD_genomes_NFE_AF
 - gnomAD_genomes_SAS_AF
 - gnomAD_genomes_controls_and_biobanks_AF
 - gnomAD_genomes_non_neuro_AF
 - gnomAD_genomes_non_cancer_AF
 - gnomAD_genomes_non_topmed_AF
 - gnomAD_genomes_controls_and_biobanks_AFR_AF
 - gnomAD_genomes_controls_and_biobanks_AMI_AF
 - gnomAD_genomes_controls_and_biobanks_AMR_AF
 - gnomAD_genomes_controls_and_biobanks_ASJ_AF
 - gnomAD_genomes_controls_and_biobanks_EAS_AF
 - gnomAD_genomes_controls_and_biobanks_FIN_AF
 - gnomAD_genomes_controls_and_biobanks_MID_AF
 - gnomAD_genomes_controls_and_biobanks_NFE_AF
 - gnomAD_genomes_controls_and_biobanks_SAS_AF
 - gnomAD_genomes_non_neuro_AFR_AF
 - gnomAD_genomes_non_neuro_AMI_AF
 - gnomAD_genomes_non_neuro_AMR_AF
 - gnomAD_genomes_non_neuro_ASJ_AF
 - gnomAD_genomes_non_neuro_EAS_AF
 - gnomAD_genomes_non_neuro_FIN_AF
 - gnomAD_genomes_non_neuro_MID_AF
 - gnomAD_genomes_non_neuro_NFE_AF
 - gnomAD_genomes_non_neuro_SAS_AF
 - gnomAD_genomes_non_cancer_AFR_AF
 - gnomAD_genomes_non_cancer_AMI_AF
 - gnomAD_genomes_non_cancer_AMR_AF
 - gnomAD_genomes_non_cancer_ASJ_AF
 - gnomAD_genomes_non_cancer_EAS_AF
 - gnomAD_genomes_non_cancer_FIN_AF
 - gnomAD_genomes_non_cancer_MID_AF
 - gnomAD_genomes_non_cancer_NFE_AF
 - gnomAD_genomes_non_cancer_SAS_AF
 - gnomAD_genomes_non_topmed_AFR_AF
 - gnomAD_genomes_non_topmed_AMI_AF
 - gnomAD_genomes_non_topmed_AMR_AF
 - gnomAD_genomes_non_topmed_ASJ_AF
 - gnomAD_genomes_non_topmed_EAS_AF
 - gnomAD_genomes_non_topmed_FIN_AF
 - gnomAD_genomes_non_topmed_MID_AF
 - gnomAD_genomes_non_topmed_NFE_AF
 - gnomAD_genomes_non_topmed_SAS_AF

nssnv_columns:
  SIFT: 0.5
  PolyPhen: 0.5
  CADD_PHRED: 20
  MetaSVM_score: 0.5   # range - -2 to 3
  FATHMM_score: 0         #weighted for human inherited- disease mutations with Disease Ontology (FATHMMori). Scores range from -18.09 to 11.0. This is for coding and MKL for non-coding variants
  MutationAssessor_score: 0   #MutationAssessor functional impact combined score (MAori). The score ranges from -5.135 to 6.49 in dbNSFP.
  PROVEAN_score: 0           # range - -14 to 13.57
  VEST4_score: 0.5           # range - 0 to 1
  GERP: 0 #ranges from -12.36 to 6.18
  MutationTaster_score: 0.5
  DANN_score: 0.5
  Eigen-PC-phred_coding: 20
  Eigen-PC-raw_coding: 0   #functional annotations. input range - -3.252 to 8.426.
  Eigen-PC-raw_coding_rankscore: 0
  Eigen-phred_coding: 20
  Eigen-raw_coding: 0
  Eigen-raw_coding_rankscore: 0
  GERP++_RS: 0
  GenoCanyon_score: 0.5
  LRT_score: 0.5  #The score ranges from 0 to 1 and a larger score signifies that the codon is more constrained or a NS is more likely to be deleterious.
  M-CAP_score: 0.5   # range - 0 to 1
  MetaLR_score: 0.5  # range - 0 to 1
  SiPhy_29way_logOdds: 15 # input range - 0 to 33.272. SiPhy score based on 29 mammals genomes. The larger the score the more conserved the site.
  fathmm-MKL_coding_score: 0.5  # range - 0 to 1. This is for non-coding variants - functional prediction tool
  integrated_fitCons_score: 0.5 # range - 0 to 1
  phastCons100way_vertebrate: 0.5
  phastCons30way_mammalian: 0.5
  phyloP100way_vertebrate: 20
  phyloP30way_mammalian: 20
  IMPACT_HIGH: 0
  IMPACT_LOW: 0
  IMPACT_MODERATE: 0
  IMPACT_MODIFIER: 0
  BIOTYPE_RNase_MRP_RNA: 0
  BIOTYPE_RNase_P_RNA: 0
  BIOTYPE_antisense_RNA: 0
  BIOTYPE_guide_RNA: 0
  BIOTYPE_lncRNA: 0
  BIOTYPE_miRNA: 0
  BIOTYPE_misc_RNA: 0
  BIOTYPE_ncRNA_pseudogene: 0
  BIOTYPE_protein_coding: 0
  BIOTYPE_scRNA: 0
  BIOTYPE_snRNA: 0
  BIOTYPE_snoRNA: 0
  BIOTYPE_telomerase_RNA: 0
  BIOTYPE_transcribed_pseudogene: 0
  BIOTYPE_nonsense_mediated_decay: 0
  BIOTYPE_polymorphic_pseudogene: 0
  BIOTYPE_IG_C_gene: 0
  BIOTYPE_non_stop_decay: 0

nssnv_median_3_0_1:
 SIFT_score: 0.020999999716877937
 SIFT_converted_rankscore: 0.5748000144958496
 SIFT4G_score: 0.04600000008940697
 SIFT4G_converted_rankscore: 0.5663999915122986
 Polyphen2_HDIV_score: 0.902999997138977
 Polyphen2_HDIV_rankscore: 0.5759900212287903
 Polyphen2_HVAR_score: 0.5410000085830688
 Polyphen2_HVAR_rankscore: 0.57014000415802
 LRT_score: 2.2000000171829015e-05
 LRT_converted_rankscore: 0.5587499737739563
 LRT_Omega: 0.0792670026421547
 MutationTaster_converted_rankscore: 0.8100100159645081
 MutationAssessor_score: 1.9850000143051147
 MutationAssessor_rankscore: 0.5646899938583374
 FATHMM_score: -0.9700000286102295
 FATHMM_converted_rankscore: 0.7842699885368347
 PROVEAN_score: -2.3399999141693115
 PROVEAN_converted_rankscore: 0.5808500051498413
 VEST4_score: 0.6420000195503235
 VEST4_rankscore: 0.7211999893188477
 MetaSVM_score: -0.3720000088214874
 MetaSVM_rankscore: 0.7289999723434448
 MetaLR_score: 0.37599998712539673
 MetaLR_rankscore: 0.7340099811553955
 Reliability_index: 10.0
 MetaRNN_score: 0.19602182507514954
 MetaRNN_rankscore: 0.35618001222610474
 M-CAP_score: 0.19680799543857574
 M-CAP_rankscore: 0.8650100231170654
 REVEL_score: 0.335999995470047
 REVEL_rankscore: 0.6969599723815918
 MutPred_score: 0.7049999833106995
 MutPred_rankscore: 0.8413800001144409
 MVP_score: 0.7887082695960999
 MVP_rankscore: 0.8119000196456909
 MPC_score: 0.48845353722572327
 MPC_rankscore: 0.5411499738693237
 PrimateAI_score: 0.607215166091919
 PrimateAI_rankscore: 0.5392299890518188
 DEOGEN2_score: 0.2666429877281189
 DEOGEN2_rankscore: 0.7485499978065491
 BayesDel_addAF_score: 0.17945000529289246
 BayesDel_addAF_rankscore: 0.7199100255966187
 BayesDel_noAF_score: 0.11684300005435944
 BayesDel_noAF_rankscore: 0.7802600264549255
 ClinPred_score: 0.3047238290309906
 ClinPred_rankscore: 0.2519800066947937
 LIST-S2_score: 0.8972100019454956
 LIST-S2_rankscore: 0.657829999923706
 CADD_raw: 3.644090414047241
 CADD_raw_rankscore: 0.6784899830818176
 CADD_phred: 25.200000762939453
 CADD_raw_hg19: 3.536958932876587
 CADD_raw_rankscore_hg19: 0.6806600093841553
 CADD_phred_hg19: 25.100000381469727
 DANN_score: 0.9947124123573303
 DANN_rankscore: 0.6636499762535095
 fathmm-MKL_coding_score: 0.9383599758148193
 fathmm-MKL_coding_rankscore: 0.5933099985122681
 fathmm-XF_coding_score: 0.47531598806381226
 fathmm-XF_coding_rankscore: 0.5192099809646606
 Eigen-raw_coding: 0.4773275852203369
 Eigen-raw_coding_rankscore: 0.6576700210571289
 Eigen-phred_coding: 4.864253044128418
 Eigen-PC-raw_coding: 0.4332945644855499
 Eigen-PC-raw_coding_rankscore: 0.6365000009536743
 Eigen-PC-phred_coding: 4.603184223175049
 GenoCanyon_score: 0.9999987483024597
 GenoCanyon_rankscore: 0.7476599812507629
 integrated_fitCons_score: 0.6752020120620728
 integrated_fitCons_rankscore: 0.5506500005722046
 integrated_confidence_value: 0.0
 GM12878_fitCons_score: 0.6271780133247375
 GM12878_fitCons_rankscore: 0.54093998670578
 GM12878_confidence_value: 0.0
 H1-hESC_fitCons_score: 0.6589829921722412
 H1-hESC_fitCons_rankscore: 0.5588099956512451
 H1-hESC_confidence_value: 0.0
 HUVEC_fitCons_score: 0.6355509757995605
 HUVEC_fitCons_rankscore: 0.5308799743652344
 HUVEC_confidence_value: 0.0
 LINSIGHT: 0.9745749831199646
 LINSIGHT_rankscore: 0.7726799845695496
 GERP++_NR: 5.329999923706055
 GERP++_RS: 4.659999847412109
 GERP++_RS_rankscore: 0.5785700082778931
 phyloP100way_vertebrate: 4.394999980926514
 phyloP100way_vertebrate_rankscore: 0.5943899750709534
 phyloP30way_mammalian: 1.0260000228881836
 phyloP30way_mammalian_rankscore: 0.45945999026298523
 phyloP17way_primate: 0.5989999771118164
 phyloP17way_primate_rankscore: 0.4025000035762787
 phastCons100way_vertebrate: 1.0
 phastCons100way_vertebrate_rankscore: 0.7163800001144409
 phastCons30way_mammalian: 0.9909999966621399
 phastCons30way_mammalian_rankscore: 0.5321999788284302
 phastCons17way_primate: 0.9679999947547913
 phastCons17way_primate_rankscore: 0.5372599959373474
 SiPhy_29way_logOdds: 13.720999717712402
 SiPhy_29way_logOdds_rankscore: 0.6220899820327759
 bStatistic: 715.0
 bStatistic_converted_rankscore: 0.5613700151443481
