# columns to be needed in dataset
columns:
  -  Chromosome
  -  Position
  -  Reference Allele
  -  Alternate Allele
  -  Consequence
  -  Gene
  -  HGNC_ID
  -  IMPACT
  -  SYMBOL
  -  Feature
  -  BIOTYPE
  -  SIFT
  -  PolyPhen
  -  CADD_PHRED
  -  CADD_RAW
  -  DANN_score
  -  Eigen-PC-phred_coding
  -  Eigen-PC-raw_coding
  -  Eigen-PC-raw_coding_rankscore
  -  Eigen-phred_coding
  -  Eigen-raw_coding
  -  Eigen-raw_coding_rankscore
  -  FATHMM_score
  -  GERP++_RS
  -  GenoCanyon_score
  -  LRT_score
  -  M-CAP_score
  -  MetaLR_score
  -  MetaSVM_score
  -  MutationAssessor_score
  -  MutationTaster_score
  -  PROVEAN_score
  -  SiPhy_29way_logOdds
  -  VEST4_score
  -  fathmm-MKL_coding_score
  -  integrated_fitCons_score
  -  phastCons100way_vertebrate
  -  phastCons30way_mammalian
  -  phyloP100way_vertebrate
  -  phyloP30way_mammalian
  -  GERP
  -  gnomADv3_AF
  -  gnomADv3_AF_afr
  -  gnomADv3_AF_afr_female
  -  gnomADv3_AF_afr_male
  -  gnomADv3_AF_ami
  -  gnomADv3_AF_ami_female
  -  gnomADv3_AF_ami_male
  -  gnomADv3_AF_amr
  -  gnomADv3_AF_amr_female
  -  gnomADv3_AF_amr_male
  -  gnomADv3_AF_asj
  -  gnomADv3_AF_asj_female
  -  gnomADv3_AF_asj_male
  -  gnomADv3_AF_eas
  -  gnomADv3_AF_eas_female
  -  gnomADv3_AF_eas_male
  -  gnomADv3_AF_female
  -  gnomADv3_AF_fin
  -  gnomADv3_AF_fin_female
  -  gnomADv3_AF_fin_male
  -  gnomADv3_AF_male
  -  gnomADv3_AF_nfe
  -  gnomADv3_AF_nfe_female
  -  gnomADv3_AF_nfe_male
  -  gnomADv3_AF_oth
  -  gnomADv3_AF_oth_female
  -  gnomADv3_AF_oth_male
  -  gnomADv3_AF_raw
  -  gnomADv3_AF_sas
  -  gnomADv3_AF_sas_female
  -  gnomADv3_AF_sas_male
  -  clinvar_CLNREVSTAT
  -  clinvar_CLNSIG

col_conv:
  -  MutationTaster_score
  -  MutationAssessor_score
  -  PROVEAN_score
  -  VEST4_score
  -  FATHMM_score
  -  GERP

ML_VAR:
  -  SYMBOL
  -  Feature
  -  Consequence
  -  Gene
  -  HGNC_ID
  -  clinvar_CLNREVSTAT
  -  clinvar_CLNSIG
  -  Chromosome
  -  Position
  -  Alternate Allele
  -  Reference Allele
  #-  ID

var:
  -  SYMBOL
  -  Feature
  -  Consequence
  -  Gene
  -  HGNC_ID
  -  clinvar_CLNREVSTAT
  -  clinvar_CLNSIG
  -  Chromosome
  -  Position
  -  Alternate Allele
  -  Reference Allele

Consequence:
  -  missense_variant
  -  missense_variant&splice_region_variant
  -  stop_gained
  -  start_lost&NMD_transcript_variant
  -  start_lost
  -  stop_gained&splice_region_variant
  -  stop_gained&NMD_transcript_variant
  -  missense_variant&splice_region_variant&NMD_transcript_variant
  -  stop_gained&splice_region_variant&NMD_transcript_variant
  -  start_lost&splice_region_variant
  -  stop_lost&splice_region_variant
  -  stop_lost&splice_region_variant&NMD_transcript_variant
  -  splice_donor_variant&missense_variant
  -  start_lost&splice_region_variant&NMD_transcript_variant

nssnv_median_3_0_1:
  gnomADv3_AF: 0
  SIFT: 0.02
  PolyPhen: 0.757
  CADD_PHRED: 25.3
  DANN_score: 0.995325924
  Eigen-PC-phred_coding: 4.859703
  Eigen-PC-raw_coding: 0.465540408
  FATHMM_score: -1.26
  GERP++_RS: 4.73
  GenoCanyon_score: 0.999998451
  LRT_score: 2.30E-05
  M-CAP_score: 0.226631
  MetaSVM_score: -0.1847
  MutationAssessor_score: 2.215
  MutationTaster_score: 1
  PROVEAN_score: -2.88
  SiPhy_29way_logOdds: 13.8644
  VEST4_score: 0.762
  fathmm-MKL_coding_score: 0.94206
  integrated_fitCons_score: 0.675202
  phastCons100way_vertebrate: 1
  phastCons30way_mammalian: 0.99
  phyloP100way_vertebrate: 4.564
  phyloP30way_mammalian: 1.026
  GERP: 5.67
  IMPACT_HIGH: 0
  BIOTYPE_IG_C_gene: 0
  BIOTYPE_non_stop_decay: 0
  BIOTYPE_polymorphic_pseudogene: 0
  BIOTYPE_protein_coding: 1
