versions:
 aloft:1.1.0
 cadd:1.0.1
 cadd_exome:1.6.1
 ccre_screen:1.0.1
 chasmplus:1.3.0
 chasmplus_group:1.2.0
 cancer_genome_interpreter:1.3.0
 civic:2023.04.01
 clinvar:2023.02.01
 clingen:1.0.1
 clinpred:1.0.0
 cosmic:94.0.0
 cosmic_gene:94.0.0
 cscape:1.0.1
 dann:1.0.2
 dann_coding:1.0.0
 dbscsnv:1.1.0
 dbsnp:154.0.2
 dgi:1.0.0
 ensembl_regulatory_build:1.0.3
 ess_gene:3.5.8
 exac_gene:0.4.0
 fathmm:2.3.7
 fathmm_xf_coding:1.0.0
 funseq2:1.0.1
 genehancer:1.1.0
 gerp:3.6.2
 ghis:3.6.0
 gnomad:2.2.0
 gnomad3:1.1.0
 gnomad_gene:2.2.1
 gtex:7.0.4
 gwas_catalog:1.0.0
 linsight:2021.01.08
 loftool:3.6.1
 lrt:1.0.0
 mavedb:1.0.1
 metalr:1.0.3
 metasvm:1.0.1
 mutation_assessor:3.1.0
 mutationtaster:1.0.0
 mutpred1:1.4.0
 mutpred_indel:1.1.0
 ncbigene:2022.08.30
 ndex:4.0.11
 ndex_chd:1.0.2
 ndex_group:1.0.0
 ndex_signor:1.0.2
 omim:1.0.0
 pangalodb:1.0.0
 phastcons:3.5.9
 phdsnpg:0.0.9
 phi:3.6.1
 phylop:3.5.10
 polyphen2:2022.10.13
 prec:3.6.0
 provean:1.1.0
 repeat:2020.10.16
 revel:2022.11.29
 rvis:3.1.0
 segway:1.2.1
 segway_group:1.0.0
 sift:1.2.0
 siphy:3.5.5
 spliceai:1.0.0
 uniprot:2020.08.10
 vest:4.4.0
 varity_r:1.0.0
